name: CoreProtect-Anti-Xray
main: net.felixkraus.AntiXray.AntiXray
version: 1.0
authors: [xilefkfelix]
depends: [CoreProtect]
description: Anti Xray Plugin
commands:
  xlu:
    usage: /xlu <name> <days>
    permission: cpantixray.use